default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: pomodoro-app-api_development


test:
  <<: *default
  database: pomodoro-app-api_test


production:
  <<: *default
  database: pomodoro-app-api_production
  username: pomodoro-app-api
  password: <%= ENV['POMODORO-APP-API_DATABASE_PASSWORD'] %>
